import turtle
BOB=turtle.Turtle()
scween=turtle.Screen()
scween.bgcolor("black")
scween.setup(500,500)
BOB.width(7)
BOB.color("teal")
BOB.forward(98)
BOB.right(90)
BOB.forward(98)
BOB.right(90)
BOB.forward(98)
BOB.right(90)
BOB.forward(98)
turtle.done()